import os
from dotenv import load_dotenv
import httpx

load_dotenv()

url = os.getenv("NEXT_API_URL")

async def save_entity(name: str, start_year: int, end_year: int, color: str, ai_generated: bool):
    """
        Saves an entity in the database of the internal API developed in next.js (a.k.a. next.js API).

        Args:
            name: Name of the entity
            start_year: Year it started existing as it is (eg: Rome only became an empire in 27BC, which is -27 here)
            end_year: Year the entity ended its existence (eg: The Roman Empire ended in 476AD, the East one should be considered as other entity)
            color: A color specific to the entity so if it matches user's request it can be painted
            ai_generated: Sets to true if the model is predicting future data and shows to the user (eg: *Generated by AI* or *Historical data*)
        
        Returns:
            The response of the next.js API in json format
    """
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(f"{url}/entities", json={
                "name": name,
                "start_year": start_year,
                "end_year": end_year,
                "color": color,
                "ai_generated": ai_generated
            })
        
        response.raise_for_status()
        
        return response.json()
    except Exception as e:
        return f"Error while calling next.js API: {str(e)}"

async def save_religion(entity_id: str | None, religion: str, start_year: int, end_year: int):
    """
        Saves an religion in the database of the internal API developed in next.js (a.k.a. next.js API).

        Args:
            entity_id: id of the entity the religion will be linked to
            religion: The religion which is being linked
            start_year: Year the entity adopted the religion
            end_year: Year the entity changed the religion
        
        Returns:
            The response of the next.js API in json format
    """
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(f"{url}/entities/{entity_id}/religions", json={
                "religion": religion,
                "start_year": start_year,
                "end_year": end_year
            })

        response.raise_for_status()

        return response.json()
    except Exception as e:
        return f"Error while calling next.js API: {str(e)}"
    
async def assign_territory_entity(entity_id: str, territory_id: str, start_year: int, end_year: int, percentage_controlled: float, geojson_boundary: dict):
    """
        Assign a modern territory to an entity in the database of the internal API developed in next.js (a.k.a. next.js API).

        Args:
            entity_id: id of the entity the territory will be assigned to
            territory_id: The id of the territory which is being linked
            start_year: Year the entity annexed the territory
            end_year: Year the entity lost the territory
            percentage_controlled: the aproximate percentage the entity controlled of the territory for the period (if the entity losts part of the territory it should be assigned a second time with different start_year, end_year and percentage_controlled)
            geojson_boundary: the data gathered from geojson to draw the the entity on the map
        
        Returns:
            The response of the next.js API in json format
    """
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(f"{url}/entities/{entity_id}/territories", json={
                "territory_id": territory_id,
                "start_year": start_year,
                "end_year": end_year,
                "percentage_controlled": percentage_controlled,
                "geojson_boundary": geojson_boundary
            })

        response.raise_for_status()

        return response.json()
    except Exception as e:
        return f"Error while calling next.js API: {str(e)}"
    
async def get_map_with_year(year: int):
    """
        Returns all the entities that existed in the requested year.

        Args:
            year: Year the user requested
            
        Returns:
            The response of the next.js API in json format
    """
    try:
        async with httpx.AsyncClient() as client:
            response = await client.get(f"{url}/map?year={year}")

        response.raise_for_status()

        return response.json()
    except Exception as e:
        return f"Error while calling next.js API: {str(e)}"